application: socrenchus
version: 1-2
runtime: python
api_version: 1

handlers:

- url: /(q/.+)?
  static_files: static/index.html
  upload: static/index.html

- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/
  login: admin

- url: /(login|rpc)
  script: handlers.py
  login: required
  
- url: /
  static_dir: static
  
builtins:
- remote_api: on