application: socrenchus
version: 1-2
runtime: python
api_version: 1

handlers:

- url: /(\#.*)?
  static_files: client/static/index.html
  upload: client/static/index.html

- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/
  login: admin

- url: /(login|logout|rpc)(.*)
  script: handlers.py
  login: required
  
- url: /
  static_dir: static
  
builtins:
- remote_api: on