application: socrenchus
version: 1-1
runtime: python
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico  

- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/
  login: admin

- url: /static
  static_dir: static

- url: /
  script: handlers.py

- url: /.*
  script: handlers.py
  login: required
  
builtins:
- remote_api: on