application: socrenchus
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /ajax/.*
  script: handlers.py
  login: required
  
- url: /static
  static_dir: static

- url: .*
  static_files: static/index.html
  upload: static/index.html
  login: required