application: socrenchus
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/
  login: admin
  
- url: /static
  static_dir: static

- url: /
  script: handlers.py

- url: /.*
  script: handlers.py
  login: required