application: socrenchus
version: 1-2
runtime: python
api_version: 1

handlers:
- url: /lib
  static_dir: client/static/lib

- url: /images
  static_dir: client/static/images

- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/
  login: admin

- url: /.*
  script: server/handlers.py

builtins:
- remote_api: on
