application: socrenchus
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /ajax/.*
  script: handlers.py
  login: required
  
- url: /static
  static_dir: static
  
- url: /experiments/1
  static_files: static/experiment1.html
  upload: static/experiment1.html
  login: required
  
- url: /q/.*
  static_files: static/stream.html
  upload: static/stream.html
  login: required

- url: .*
  static_files: static/index.html
  upload: static/index.html