class Tests
  #insert new post - not tested for client
  try_client_insert_post: ->
    content = "This post generated by try_client_insert_post"
    Posts.insert({content: content})
    tron.log('Inserting randomized post with content:\n', content)
  
  ###  
  #insert new tag in random post - untested
  try_client_insert_tag: ->
    id = Meteor.call('get_user_id')
    tag_text = Meteor.uuid()
    q = {'$set': {}}
    q['$set']["my_tags.#{tag_text}"] = 1
    #tron.log('Inserting randomized tag:\n', q, '\n...with author_id:', id)
    Posts.update({ '_id': id}, q)
  ###
  
  ###  
  #update existing tag in random post - not working...
  #add user to an existing tag
  try_client_update_tag: ->
    post = Posts.findOne()
    q = {'$set': {}}
    for tag of post.tags
      tron.log("Updating tag \"#{tag}\" in post \"#{post._id}\"")
      q['$set']["my_tags.#{tag}"] = 1
      # = new ServerPost(  )
      Posts.update({ '_id': post._id }, q)
      break
  ###
  
tron.test( new Tests() )